apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
spec:
  containers:
  - name: busybox-container
    image: busybox
    command: ["sleep", "3600"] # Keep the container running for 1 hour (3600 seconds)
  restartPolicy: Always
